<?php

namespace Database\Seeders;

use App\Models\QuanAn;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class QuanAnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('quan_ans')->delete();
        DB::table('quan_ans')->truncate();

        DB::table('quan_ans')->insert([
            // QUÁN CAFE & ĐỒ UỐNG (1-10)
            [
                'id' => 1,
                'email' => 'highlands@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400101234',
                'ten_quan_an' => 'Highlands Coffee',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '23:00:00',
                'dia_chi' => '240 Trần Phú, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 108.2251365,  // longitude
                'toa_do_y' => 16.0565052,   // latitude
                'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWfJUWKecfedJtsuTOPzmzy51L7szK8FDYfw&s',
                'so_dien_thoai' => '0905123456',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 2,
                'email' => 'phuchung@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400201234',
                'ten_quan_an' => 'Trà Sữa Phúc Hưng',
                'gio_mo_cua' => '08:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '156 Hải Phòng, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.074230,
                'toa_do_y' => 108.220280,
                'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqNHTIVrbAZwMmUi24F9koO4whaBIOIrIfZA&s',
                'so_dien_thoai' => '0905234567',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 3,
                'email' => 'dinhtitrasu@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400301234',
                'ten_quan_an' => 'Dinhtea - Trà Sữa',
                'gio_mo_cua' => '07:00:00',
                'gio_dong_cua' => '23:00:00',
                'dia_chi' => '45 Nguyễn Văn Linh, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.062500,
                'toa_do_y' => 108.218300,
                'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlAP1CRvpgbbSB8dYnblsDOcx8lDZssFhT5Q&s',
                'so_dien_thoai' => '0905345678',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 4,
                'email' => 'gongcha@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400401234',
                'ten_quan_an' => 'Gong Cha',
                'gio_mo_cua' => '08:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '78 Lê Duẩn, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.075600,
                'toa_do_y' => 108.221600,
                'hinh_anh' => 'https://thietkewebchuyen.com/wp-content/uploads/gong-cha-logo-4-1.jpg',
                'so_dien_thoai' => '0905456789',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 5,
                'email' => 'nuoceptraicay@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400501234',
                'ten_quan_an' => 'Nước Ép & Sinh Tố Sài Gòn',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '123 Trần Kế Xương, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.067600,
                'toa_do_y' => 108.220800,
                'hinh_anh' => 'https://hoaquafuji.com/storage/app/media/nuoc-ep-trai-cay-00-min.jpg',
                'so_dien_thoai' => '0905567890',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN CƠM TẤM (6-15)
            [
                'id' => 6,
                'email' => 'comtambasac@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400601234',
                'ten_quan_an' => 'Cơm Tấm Bà Sáu',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '89 Hoàng Văn Thụ, Quận Liên Chiểu, Đà Nẵng',
                'id_quan_huyen' => 75,
                'toa_do_x' => 16.069500,
                'toa_do_y' => 108.220300,
                'hinh_anh' => 'https://ik.imagekit.io/tvlk/blog/2024/10/com-tam-2.png?tr=q-70,c-at_max,w-1000,h-600',
                'so_dien_thoai' => '0905678901',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 7,
                'email' => 'comtamsuonngon@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400701234',
                'ten_quan_an' => 'Cơm Tấm Sườn Ngon',
                'gio_mo_cua' => '06:30:00',
                'gio_dong_cua' => '20:30:00',
                'dia_chi' => '234 Phan Châu Trinh, Huyện Hòa Vang, Đà Nẵng',
                'id_quan_huyen' => 79,
                'toa_do_x' => 16.059200,
                'toa_do_y' => 108.217800,
                'hinh_anh' => 'https://nvhphunu.vn/wp-content/uploads/2023/12/Com-Tam-Suon-Nuong-Cach-Lam-Dam-Da-Thom-Ngon.jpeg',
                'so_dien_thoai' => '0905789012',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 8,
                'email' => 'comgadanang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400801234',
                'ten_quan_an' => 'Cơm Gà Đà Nẵng',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '145 Trần Phú, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 16.067100,
                'toa_do_y' => 108.220000,
                'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDv8mcrMIpF6beyup8BA4GOeQt2Z-J2q2wog&s',
                'so_dien_thoai' => '0905890123',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 9,
                'email' => 'comchiendanang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0400901234',
                'ten_quan_an' => 'Cơm Chiên Đà Nẵng',
                'gio_mo_cua' => '10:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '67 Lê Lợi, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.072200,
                'toa_do_y' => 108.218400,
                'hinh_anh' => 'https://i.ytimg.com/vi/ZbSbc9Z8K6E/maxresdefault.jpg',
                'so_dien_thoai' => '0906901234',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 10,
                'email' => 'comvanphong@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401001234',
                'ten_quan_an' => 'Cơm Văn Phòng Bình Dân',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '190 Nguyễn Chí Thanh, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.073500,
                'toa_do_y' => 108.220700,
                'hinh_anh' => 'https://menuonline.vn/images/upload/news/901460992-com-trua-van-phong-0.jpg',
                'so_dien_thoai' => '0907012345',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN BÚN & PHỞ (11-20)
            [
                'id' => 11,
                'email' => 'bunbohuedanang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401101234',
                'ten_quan_an' => 'Bún Bò Huế Đà Nẵng',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '123 Hoàng Diệu, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.060000,
                'toa_do_y' => 108.209500,
                'hinh_anh' => 'https://static.vinwonders.com/production/bun-bo-hue-topbanner.jpg',
                'so_dien_thoai' => '0907123456',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 12,
                'email' => 'bunthitnuongngon@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401201234',
                'ten_quan_an' => 'Bún Thịt Nướng Ngon',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '456 Ông Ích Khiêm, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.068300,
                'toa_do_y' => 108.209600,
                'hinh_anh' => 'https://static.vinwonders.com/production/bun-thit-nuong-ha-noi-4.jpg',
                'so_dien_thoai' => '0907234567',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 13,
                'email' => 'bunchacahon@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401301234',
                'ten_quan_an' => 'Bún Chả Cá Hờn',
                'gio_mo_cua' => '06:30:00',
                'gio_dong_cua' => '20:30:00',
                'dia_chi' => '113/3 Nguyễn Chí Thanh, Quận Liên Chiểu, Đà Nẵng',
                'id_quan_huyen' => 75,
                'toa_do_x' => 16.073500,
                'toa_do_y' => 108.220700,
                'hinh_anh' => 'https://toplist.vn/images/800px/bun-cha-ca-hon-1090300.jpg',
                'so_dien_thoai' => '0907345678',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 14,
                'email' => 'bunmamngon@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401401234',
                'ten_quan_an' => 'Bún Mắm Ngon',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '23/14 Trần Kế Xương, Huyện Hòa Vang, Đà Nẵng',
                'id_quan_huyen' => 79,
                'toa_do_x' => 16.067819,
                'toa_do_y' => 108.220950,
                'hinh_anh' => 'https://cdn.tgdd.vn/Files/2019/06/27/1175792/cach-nau-bun-bo-tai-an-mot-cai-la-te-tai-ca-nguoi-202208301428003234.jpg',
                'so_dien_thoai' => '0907456789',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 15,
                'email' => 'phobodanang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401501234',
                'ten_quan_an' => 'Phở Bò Đà Nẵng',
                'gio_mo_cua' => '05:30:00',
                'gio_dong_cua' => '14:00:00',
                'dia_chi' => '89 Đoàn Thị Điểm, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 16.072400,
                'toa_do_y' => 108.222300,
                'hinh_anh' => 'https://static.vinwonders.com/2022/11/pho_da_nang.jpg',
                'so_dien_thoai' => '0907567890',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN MÌ QUẢNG (16-20)
            [
                'id' => 16,
                'email' => 'miquang1a@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401601234',
                'ten_quan_an' => 'Mì Quảng 1A',
                'gio_mo_cua' => '07:00:00',
                'gio_dong_cua' => '20:30:00',
                'dia_chi' => '1 Hải Phòng, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.074230,
                'toa_do_y' => 108.220280,
                'hinh_anh' => 'https://cdn.khamphadanang.vn/wp-content/uploads/2024/02/mi-quang-1a-hai-phong-3.jpg?strip=all&lossy=1&ssl=1',
                'so_dien_thoai' => '0907678901',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 17,
                'email' => 'miquangbeptrang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401701234',
                'ten_quan_an' => 'Mì Quảng Bếp Trang',
                'gio_mo_cua' => '08:00:00',
                'gio_dong_cua' => '21:30:00',
                'dia_chi' => '441 Ông Ích Khiêm, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.068500,
                'toa_do_y' => 108.209800,
                'hinh_anh' => 'https://cdn.khamphadanang.vn/wp-content/uploads/2024/01/mi-quang-ech-bep-trang-2.jpg?strip=all&lossy=1&ssl=1',
                'so_dien_thoai' => '0907789012',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 18,
                'email' => 'miquangthi@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401801234',
                'ten_quan_an' => 'Mì Quảng Thi',
                'gio_mo_cua' => '07:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '66 Lê Lợi, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.072200,
                'toa_do_y' => 108.218400,
                'hinh_anh' => 'https://nld.mediacdn.vn/291774122806476800/2024/8/12/quan-my-quang-da-nang-17234413849951823742675.jpg',
                'so_dien_thoai' => '0907890123',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 19,
                'email' => 'miquangba@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0401901234',
                'ten_quan_an' => 'Mì Quảng Bà',
                'gio_mo_cua' => '07:30:00',
                'gio_dong_cua' => '20:30:00',
                'dia_chi' => '156 Hải Phòng, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.074800,
                'toa_do_y' => 108.220600,
                'hinh_anh' => 'https://img.mservice.com.vn/common/u/2e02fb5fe4f64fb55bc713540643c6f8eae702d101cea8c59afc49cfc505fc37/a5876a61-717c-4b01-818b-c5bc6c7ff3058xvjq6z1.jpeg',
                'so_dien_thoai' => '0907901234',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 20,
                'email' => 'miquanghai@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402001234',
                'ten_quan_an' => 'Mì Quảng Hải',
                'gio_mo_cua' => '06:30:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '234 Trần Phú, Quận Liên Chiểu, Đà Nẵng',
                'id_quan_huyen' => 75,
                'toa_do_x' => 16.067500,
                'toa_do_y' => 108.220300,
                'hinh_anh' => 'https://mia.vn/media/uploads/blog-du-lich/ghe-lai-thuong-thuc-mi-quang-so-1a-hai-phong-da-nang-mon-an-dai-dien-van-hoa-am-thuc-mien-trung-03-1636959551.jpg',
                'so_dien_thoai' => '0908012345',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN BÁNH MÌ (21-25)
            [
                'id' => 21,
                'email' => 'banhmibalan@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402101234',
                'ten_quan_an' => 'Bánh Mì Bà Lan',
                'gio_mo_cua' => '05:30:00',
                'gio_dong_cua' => '21:30:00',
                'dia_chi' => '85 Nguyễn Văn Linh, Huyện Hòa Vang, Đà Nẵng',
                'id_quan_huyen' => 79,
                'toa_do_x' => 16.063700,
                'toa_do_y' => 108.214900,
                'hinh_anh' => 'https://mms.img.susercontent.com/vn-11134513-7r98o-lsvbxmbbbtehaa@resize_ss1242x600!@crop_w1242_h600_cT',
                'so_dien_thoai' => '0908123456',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 22,
                'email' => 'banhmidanang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402201234',
                'ten_quan_an' => 'Bánh Mì Đà Nẵng',
                'gio_mo_cua' => '05:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '67 Trần Phú, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 16.066700,
                'toa_do_y' => 108.220400,
                'hinh_anh' => 'https://anhquanbakery.com/uploads/article/top-5-tiem-banh-mi-noi-tieng-nhat-da-nang-1590993955.jpg',
                'so_dien_thoai' => '0908234567',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 23,
                'email' => 'banhmiphuong@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402301234',
                'ten_quan_an' => 'Bánh Mì Phượng',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '123 Phan Châu Trinh, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.059100,
                'toa_do_y' => 108.217600,
                'hinh_anh' => 'https://yummyday.vn/uploads/images/banh-mi-thit-nuong-6.jpg',
                'so_dien_thoai' => '0908345678',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 24,
                'email' => 'banhmixiu@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402401234',
                'ten_quan_an' => 'Bánh Mì Xíu Mại',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '156 Hoàng Văn Thụ, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.069700,
                'toa_do_y' => 108.220500,
                'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLv7gQ0BvPeMQZh2fZZ0KCE-ccUSdLSQ8Bgg&s',
                'so_dien_thoai' => '0908456789',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 25,
                'email' => 'banhmihuebinh@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402501234',
                'ten_quan_an' => 'Bánh Mì Huệ Bình',
                'gio_mo_cua' => '05:30:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '234 Lê Duẩn, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.075400,
                'toa_do_y' => 108.221300,
                'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/09/06/1380700/cach-lam-banh-mi-heo-quay-thom-ngon-cho-bua-sang-dinh-duong-202201041047079624.jpg',
                'so_dien_thoai' => '0908567890',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN BÁNH XÈO & BÁNH CUỐN (26-30)
            [
                'id' => 26,
                'email' => 'banhxeonamhien@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402601234',
                'ten_quan_an' => 'Bánh Xèo Năm Hiền',
                'gio_mo_cua' => '10:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '46 Phan Thanh, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.065500,
                'toa_do_y' => 108.206800,
                'hinh_anh' => 'https://vivuvietnam.org/wp-content/uploads/2024/05/banh-xeo-tom-nhay-nam-hien-da-nang.jpg',
                'so_dien_thoai' => '0908678901',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 27,
                'email' => 'banhcuontienhung@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402701234',
                'ten_quan_an' => 'Bánh Cuốn Tiến Hưng',
                'gio_mo_cua' => '06:30:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '190 Trần Phú, Quận Liên Chiểu, Đà Nẵng',
                'id_quan_huyen' => 75,
                'toa_do_x' => 16.067300,
                'toa_do_y' => 108.220100,
                'hinh_anh' => 'https://danangbest.com/upload_content/banh-cuon.webp',
                'so_dien_thoai' => '0908789012',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 28,
                'email' => 'banhtrangcuon@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402801234',
                'ten_quan_an' => 'Bánh Tráng Cuốn Bà Hường',
                'gio_mo_cua' => '09:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '126 Duy Tân, Huyện Hòa Vang, Đà Nẵng',
                'id_quan_huyen' => 79,
                'toa_do_x' => 16.059700,
                'toa_do_y' => 108.218200,
                'hinh_anh' => 'https://cdn.hanamihotel.com/wp-content/uploads/2022/12/Banh-trang-cuon-thit-heo-Da-Nang.jpg?strip=all&lossy=1&ssl=1',
                'so_dien_thoai' => '0908890123',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 29,
                'email' => 'banhcanhbathu@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0402901234',
                'ten_quan_an' => 'Bánh Canh Bà Thu',
                'gio_mo_cua' => '06:30:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '22 Nguyễn Chí Thanh, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 16.073600,
                'toa_do_y' => 108.220900,
                'hinh_anh' => 'https://cdn.hanamihotel.com/wp-content/uploads/2023/07/file_restaurant_photo_kfvg_16349-03df792e-211023070127-1024x495.webp?strip=all&lossy=1&ssl=1',
                'so_dien_thoai' => '0908901234',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 30,
                'email' => 'banhdappct@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403001234',
                'ten_quan_an' => 'Bánh Đập Phan Châu Trinh',
                'gio_mo_cua' => '07:00:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '251 Phan Châu Trinh, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.059000,
                'toa_do_y' => 108.217500,
                'hinh_anh' => 'https://vietluxtour.com/Upload/images/2024/CamNangDuLich/B%C3%A1nh%20%C4%91%E1%BA%ADp%20%C4%90%C3%A0%20N%E1%BA%B5n/banh-dap-da-nang%20(4)-min.jpg',
                'so_dien_thoai' => '0909012345',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN ĐỒ ĂN VẶT & HẢI SẢN (31-40)
            [
                'id' => 31,
                'email' => 'xoichiennguyen@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403101234',
                'ten_quan_an' => 'Xôi Chiên Nguyên',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '89 Lê Lợi, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.072100,
                'toa_do_y' => 108.218300,
                'hinh_anh' => 'https://cdn.tgdd.vn/Files/2014/10/09/572276/bi-quyet-lam-xoi-chien-cang-an-cang-ghien--7.jpg',
                'so_dien_thoai' => '0909123456',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 32,
                'email' => 'ochutcaybang@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403201234',
                'ten_quan_an' => 'Ốc Hút Cây Bàng',
                'gio_mo_cua' => '16:00:00',
                'gio_dong_cua' => '23:00:00',
                'dia_chi' => '59 Ông Ích Khiêm, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.069800,
                'toa_do_y' => 108.209000,
                'hinh_anh' => 'https://static.vinwonders.com/production/oc-da-nang-0_optimized.jpg',
                'so_dien_thoai' => '0909234567',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 33,
                'email' => 'haisancuabien@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403301234',
                'ten_quan_an' => 'Hải Sản Cua Biển',
                'gio_mo_cua' => '10:00:00',
                'gio_dong_cua' => '23:00:00',
                'dia_chi' => '112 Võ Nguyên Giáp, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.059620,
                'toa_do_y' => 108.249770,
                'hinh_anh' => 'https://vn1.vdrive.vn/haisancuabien.com/2022/02/nha-ha-ng-chuye-n-cung-ca-p-ha-i-sa-n-tu-o-i-ngon-ta-i-nam-di-nh-go-i-09873161024-56492.jpeg',
                'so_dien_thoai' => '0909345678',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 34,
                'email' => 'bethuicaumongro@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403401234',
                'ten_quan_an' => 'Bê Thui Cầu Mống',
                'gio_mo_cua' => '10:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '8 Bắc Sơn, Quận Liên Chiểu, Đà Nẵng',
                'id_quan_huyen' => 75,
                'toa_do_x' => 16.043200,
                'toa_do_y' => 108.187500,
                'hinh_anh' => 'https://statics.vinpearl.com/be-thui-cau-mong-thumbnail_1634017352.jpg',
                'so_dien_thoai' => '0909456789',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 35,
                'email' => 'chethai@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403501234',
                'ten_quan_an' => 'Chè Thái Sài Gòn',
                'gio_mo_cua' => '08:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '45 Hoàng Văn Thụ, Huyện Hòa Vang, Đà Nẵng',
                'id_quan_huyen' => 79,
                'toa_do_x' => 16.069400,
                'toa_do_y' => 108.220200,
                'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/09/08/1381072/cach-lam-che-thai-sau-rieng-thom-ngon-an-la-ghien-202109081353585993.jpg',
                'so_dien_thoai' => '0909567890',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],

            // QUÁN ĂN CHAY & MÓN ĐẶC SẢN (36-40)
            [
                'id' => 36,
                'email' => 'comchayhuongsen@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403601234',
                'ten_quan_an' => 'Cơm Chay Hương Sen',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '20:00:00',
                'dia_chi' => '234 Nguyễn Văn Linh, Quận Hải Châu, Đà Nẵng',
                'id_quan_huyen' => 74,
                'toa_do_x' => 16.062000,
                'toa_do_y' => 108.218500,
                'hinh_anh' => 'https://thuanchay.vn/congdong/wp-content/uploads/2025/07/Huong-sen-gv-12.jpg',
                'so_dien_thoai' => '0909678901',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 37,
                'email' => 'quanbabe@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403701234',
                'ten_quan_an' => 'Quán Bà Bé',
                'gio_mo_cua' => '07:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '100 Hoàng Văn Thụ, Quận Sơn Trà, Đà Nẵng',
                'id_quan_huyen' => 77,
                'toa_do_x' => 16.069500,
                'toa_do_y' => 108.220300,
                'hinh_anh' => 'https://hoangviettravel.vn/wp-content/uploads/2020/04/banh-beo-ba-be-da-nang-1-1.jpg',
                'so_dien_thoai' => '0909789012',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 38,
                'email' => 'quanlong@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403801234',
                'ten_quan_an' => 'Quán Lòng Đà Nẵng',
                'gio_mo_cua' => '06:00:00',
                'gio_dong_cua' => '14:00:00',
                'dia_chi' => '78 Ông Ích Khiêm, Quận Thanh Khê, Đà Nẵng',
                'id_quan_huyen' => 78,
                'toa_do_x' => 16.068700,
                'toa_do_y' => 108.209700,
                'hinh_anh' => 'https://imgamp.phunutoday.vn/files/dataimages/201608/11/original/cach-lam-mon-goi-long-heo-tron-chua-cay-thom-ngon-tai-nha-phunutodayvn_1470934242.jpg',
                'so_dien_thoai' => '0909890123',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 39,
                'email' => 'quantran@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0403901234',
                'ten_quan_an' => 'Quán Trần',
                'gio_mo_cua' => '09:00:00',
                'gio_dong_cua' => '21:00:00',
                'dia_chi' => '4 Lê Duẩn, Quận Ngũ Hành Sơn, Đà Nẵng',
                'id_quan_huyen' => 76,
                'toa_do_x' => 16.075400,
                'toa_do_y' => 108.221300,
                'hinh_anh' => 'https://mia.vn/media/uploads/blog-du-lich/am-thuc-tran-da-nang-dam-da-huong-vi-xu-quang-03-1636209837.jpeg',
                'so_dien_thoai' => '0909901234',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
            [
                'id' => 40,
                'email' => 'banhkem@gmail.com',
                'password' => bcrypt('123456'),
                'ma_so_thue' => '0404001234',
                'ten_quan_an' => 'Tiệm Bánh Kem Ngọt Ngào',
                'gio_mo_cua' => '08:00:00',
                'gio_dong_cua' => '22:00:00',
                'dia_chi' => '156 Trần Phú, Quận Cẩm Lệ, Đà Nẵng',
                'id_quan_huyen' => 73,
                'toa_do_x' => 16.067200,
                'toa_do_y' => 108.220100,
                'hinh_anh' => 'https://cdn.tgdd.vn/2020/12/CookProduct/1260-1200x643-68.jpg',
                'so_dien_thoai' => '0910012345',
                'tong_tien' => 0,
                'tinh_trang' => 1,
                'is_active' => 1
            ],
        ]);
    }
}
