<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VoucherSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        DB::table('vouchers')->truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        $img = 'https://thuvienmuasam.com/uploads/default/original/2X/e/eb5195361a1c0e308b3acf2426984e87fb5f8cb7.jpeg';

        DB::table('vouchers')->insert([

            // =====================================================
            // NHÓM 1: VOUCHER TOÀN HỆ THỐNG (id_quan_an = 0)
            // =====================================================

            // --- Giảm % ---
            ['id'=>1,'ma_code'=>'WELCOME20',    'ten_voucher'=>'Chào mừng khách mới - Giảm 20%',          'mo_ta'=>'Dành cho khách hàng đặt đơn lần đầu tiên',             'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>500, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>2,'ma_code'=>'SHOPEFOOD10',  'ten_voucher'=>'ShopeFood Giảm 10% Toàn Sàn',             'mo_ta'=>'Áp dụng tất cả các quán, không thời hạn',             'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>3,'ma_code'=>'SUPER15',      'ten_voucher'=>'Super Deal Giảm 15%',                     'mo_ta'=>'Ưu đãi đặc biệt cuối tuần toàn sàn',                 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-03-01','thoi_gian_ket_thuc'=>'2026-03-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>200, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>4,'ma_code'=>'TETSALE25',    'ten_voucher'=>'Tết Bính Ngọ - Giảm sốc 25%',            'mo_ta'=>'Mừng Tết Nguyên Đán, ưu đãi liên tiếp 30 ngày',       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2026-01-20','thoi_gian_ket_thuc'=>'2026-02-20','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>25,'so_tien_toi_da'=>60000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>1000,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>5,'ma_code'=>'BLACKFRIDAY50','ten_voucher'=>'Black Friday - Giảm 50% Khủng!',          'mo_ta'=>'Deal mạnh nhất năm, chỉ 10 ngày cuối tháng 11',       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-11-20','thoi_gian_ket_thuc'=>'2025-11-30','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>50,'so_tien_toi_da'=>100000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>500, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>6,'ma_code'=>'MIDAUTUMN30',  'ten_voucher'=>'Trung Thu - Giảm 30%',                   'mo_ta'=>'Ưu đãi mùa trăng rằm tháng 8',                       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-09-05','thoi_gian_ket_thuc'=>'2025-09-15','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>30,'so_tien_toi_da'=>70000,'don_hang_toi_thieu'=>120000,'tinh_trang'=>1,'so_luot_toi_da'=>400, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>7,'ma_code'=>'SUMMER20',     'ten_voucher'=>'Ưu Đãi Mùa Hè 20%',                     'mo_ta'=>'Mát lành mùa hè với ưu đãi hấp dẫn',                 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-06-01','thoi_gian_ket_thuc'=>'2025-08-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>8,'ma_code'=>'FLASHHOUR35',  'ten_voucher'=>'Flash 1 Giờ - Giảm 35%',                'mo_ta'=>'Chỉ trong 1 tiếng đồng hồ, không bỏ lỡ!',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-07-15','thoi_gian_ket_thuc'=>'2025-07-16','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>35,'so_tien_toi_da'=>80000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>100, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>9,'ma_code'=>'PAYDAY5',      'ten_voucher'=>'Ngày Lương - Giảm 5%',                   'mo_ta'=>'Ngày cuối tháng nhận lương, thưởng thức ngay!',       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>5, 'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>40000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>10,'ma_code'=>'WEEKEND12',   'ten_voucher'=>'Cuối Tuần Vui Giảm 12%',                'mo_ta'=>'Mỗi cuối tuần đều có ưu đãi, đặt ngay thôi nào!',    'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>12,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>11,'ma_code'=>'VALENTINE15', 'ten_voucher'=>'Valentine Ngọt Ngào 15%',               'mo_ta'=>'14/2 yêu thương, chia sẻ ưu đãi cùng người thân',   'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2026-02-10','thoi_gian_ket_thuc'=>'2026-02-14','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>35000,'don_hang_toi_thieu'=>70000, 'tinh_trang'=>1,'so_luot_toi_da'=>300, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>12,'ma_code'=>'VIP40',        'ten_voucher'=>'Khách VIP - Giảm 40%',                 'mo_ta'=>'Dành riêng cho khách VIP thân thiết của ShopeFood', 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>40,'so_tien_toi_da'=>90000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>50,  'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>5,'loai_voucher'=>'private'],

            // --- Giảm tiền mặt ---
            ['id'=>13,'ma_code'=>'SAVE20K',     'ten_voucher'=>'Giảm Ngay 20K',                         'mo_ta'=>'Giảm thẳng 20.000đ không điều kiện phức tạp',        'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>20000,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>14,'ma_code'=>'GIFT50K',     'ten_voucher'=>'Quà Tặng 50K',                          'mo_ta'=>'Ưu đãi đặc biệt, giảm 50.000đ cho đơn hàng lớn',    'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>50000,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>200, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>15,'ma_code'=>'NEWYEAR70K',  'ten_voucher'=>'Mừng Năm Mới Giảm 70K',                'mo_ta'=>'Mừng năm mới 2026, giảm 70.000đ cho đơn từ 120k',   'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-12-25','thoi_gian_ket_thuc'=>'2026-01-10','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>70000,'so_tien_toi_da'=>70000,'don_hang_toi_thieu'=>120000,'tinh_trang'=>1,'so_luot_toi_da'=>300, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>16,'ma_code'=>'BIRTHDAY100K','ten_voucher'=>'Sinh Nhật ShopeFood 100K',              'mo_ta'=>'Kỉ niệm thành lập, tặng mã giảm 100.000đ',           'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-04-01','thoi_gian_ket_thuc'=>'2025-04-07','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>100000,'so_tien_toi_da'=>100000,'don_hang_toi_thieu'=>200000,'tinh_trang'=>1,'so_luot_toi_da'=>100, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>17,'ma_code'=>'FREE30K',     'ten_voucher'=>'Miễn Phí 30K',                          'mo_ta'=>'Giảm 30.000đ cho đơn đầu tháng',                    'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>30000,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 2: VOUCHER THEO QUÁN CỤ THỂ
            // =====================================================

            // Quán 1 - Highlands Coffee
            ['id'=>18,'ma_code'=>'HLC10',        'ten_voucher'=>'Highlands - Giảm 10% Cà Phê',           'mo_ta'=>'Thưởng thức cafe Highlands với ưu đãi 10%',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>1, 'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>19,'ma_code'=>'HLC20K',        'ten_voucher'=>'Highlands - Giảm 20K Đồ Uống',          'mo_ta'=>'Giảm 20k khi gọi 2 ly Highlands trở lên',           'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-06-01','thoi_gian_ket_thuc'=>'2025-08-31','id_quan_an'=>1, 'loai_giam'=>0,'so_giam_gia'=>20000,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>500, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // Quán 2 - Trà Sữa Phúc Hưng
            ['id'=>20,'ma_code'=>'PHUCHUNG15',   'ten_voucher'=>'Phúc Hưng - Giảm 15% Trà Sữa',          'mo_ta'=>'Uống trà sữa Phúc Hưng, vị ngon - giá rẻ hơn',     'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-06-30','id_quan_an'=>2, 'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // Quán 6 - Cơm Tấm Bà Sáu
            ['id'=>21,'ma_code'=>'COMTAM10',     'ten_voucher'=>'Cơm Tấm Bà Sáu - Giảm 10%',            'mo_ta'=>'Cơm tấm ngon, giảm thêm 10% cho bữa trưa',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>6, 'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>22,'ma_code'=>'COMTAM25K',    'ten_voucher'=>'Cơm Tấm Bà Sáu - Tặng 25K',            'mo_ta'=>'Giảm 25.000đ cho đơn cơm tấm từ 80k',               'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-05-01','thoi_gian_ket_thuc'=>'2025-07-31','id_quan_an'=>6, 'loai_giam'=>0,'so_giam_gia'=>25000,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>200, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // Quán 8 - Cơm Gà Đà Nẵng
            ['id'=>23,'ma_code'=>'COMGA20',      'ten_voucher'=>'Cơm Gà ĐN - Giảm 20%',                 'mo_ta'=>'Gà giòn - cơm thơm, ưu đãi mỗi ngày',              'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>8, 'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // Quán 11 - Bún Bò Huế
            ['id'=>24,'ma_code'=>'BUNBO15',      'ten_voucher'=>'Bún Bò Huế - Giảm 15%',                'mo_ta'=>'Tô bún bò đậm đà chuẩn Huế, giảm ngay 15%',        'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>11,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>25,'ma_code'=>'BUNBO30K',     'ten_voucher'=>'Bún Bò Huế - Giảm 30K',                'mo_ta'=>'Giảm 30.000đ, no nê tô bún bò đặc biệt',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-09-01','thoi_gian_ket_thuc'=>'2025-11-30','id_quan_an'=>11,'loai_giam'=>0,'so_giam_gia'=>30000,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>90000, 'tinh_trang'=>1,'so_luot_toi_da'=>300, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // Quán 15 - Phở Bò Đà Nẵng
            ['id'=>26,'ma_code'=>'PHO10',        'ten_voucher'=>'Phở Bò ĐN - Giảm 10%',                 'mo_ta'=>'Tô phở bò chuẩn vị Hà Nội, ưu đãi 10%',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>15,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // Quán 16 - Mì Quảng 1A
            ['id'=>27,'ma_code'=>'MIQUANG1A',    'ten_voucher'=>'Mì Quảng 1A - Giảm 20%',               'mo_ta'=>'Mì Quảng Đà Nẵng đặc sản, giảm ngay 20%',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>16,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>28,'ma_code'=>'MIQUANG50K',   'ten_voucher'=>'Mì Quảng 1A - Tặng 50K',               'mo_ta'=>'Giảm 50.000đ khi đặt combo mì quảng gia đình',      'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-08-01','thoi_gian_ket_thuc'=>'2025-10-31','id_quan_an'=>16,'loai_giam'=>0,'so_giam_gia'=>50000,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>100, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // Quán 26 - Bánh Xèo Năm Hiền
            ['id'=>29,'ma_code'=>'BANHXEO10',   'ten_voucher'=>'Bánh Xèo Năm Hiền - Giảm 10%',          'mo_ta'=>'Bánh xèo giòn rụm đặc sản Đà Nẵng, ưu đãi 10%',   'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>26,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // Quán 32 - Ốc Hút Cây Bàng
            ['id'=>30,'ma_code'=>'OCHUT15',      'ten_voucher'=>'Ốc Hút Cây Bàng - Giảm 15%',           'mo_ta'=>'Ốc hút đặc sản Đà Nẵng, giảm 15% mỗi chiều',       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>32,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>35000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 3: VOUCHER THEO DỊP ĐẶC BIỆT
            // =====================================================

            ['id'=>31,'ma_code'=>'PHUNU8M3',    'ten_voucher'=>'Ngày Phụ Nữ 8/3 - Giảm 30%',           'mo_ta'=>'Tri ân phái đẹp, ưu đãi khủng ngày 8/3',           'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2026-03-06','thoi_gian_ket_thuc'=>'2026-03-10','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>30,'so_tien_toi_da'=>60000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>500, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>32,'ma_code'=>'QUOCTE20T4',  'ten_voucher'=>'Ngày Thống Nhất - Giảm 30/4%',          'mo_ta'=>'Chào mừng ngày 30/4 thống nhất, giảm 30%',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-04-28','thoi_gian_ket_thuc'=>'2025-05-02','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>30,'so_tien_toi_da'=>70000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>1000,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>33,'ma_code'=>'NGAYLAODONG', 'ten_voucher'=>'Ngày Lao Động 1/5 Giảm 20%',           'mo_ta'=>'Nghỉ lễ thật vui, không cần nấu ăn, giao tận nơi!', 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-05-01','thoi_gian_ket_thuc'=>'2025-05-03','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>70000, 'tinh_trang'=>1,'so_luot_toi_da'=>2000,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>34,'ma_code'=>'DOCDAP2T9',   'ten_voucher'=>'Độc Lập 2/9 - Giảm 29%',               'mo_ta'=>'Mừng ngày Quốc Khánh, ưu đãi con số 29',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-09-01','thoi_gian_ket_thuc'=>'2025-09-03','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>29,'so_tien_toi_da'=>65000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>1000,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>35,'ma_code'=>'NOEL25K',     'ten_voucher'=>'Giáng Sinh Ngọt Ngào 25K',              'mo_ta'=>'Merry Xmas! Tặng 25.000đ cho đơn mùa Giáng Sinh',  'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-12-20','thoi_gian_ket_thuc'=>'2025-12-26','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>25000,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>500, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 4: VOUCHER FREESHIP
            // =====================================================

            ['id'=>36,'ma_code'=>'FREESHIP1',   'ten_voucher'=>'Freeship - Giảm Phí Ship 15K',          'mo_ta'=>'Giảm 15.000đ phí giao hàng cho mọi đơn',           'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>15000,'so_tien_toi_da'=>15000,'don_hang_toi_thieu'=>0,    'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>37,'ma_code'=>'FREESHIP2',   'ten_voucher'=>'Freeship Max - Giảm Ship 30K',           'mo_ta'=>'Giảm 30.000đ phí ship cho đơn từ 100k',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>30000,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>38,'ma_code'=>'SHIP0',       'ten_voucher'=>'Miễn Phí Ship Toàn Bộ 50K',             'mo_ta'=>'Giảm toàn bộ tiền ship tối đa 50.000đ',             'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-03-01','thoi_gian_ket_thuc'=>'2025-03-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>50000,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>120000,'tinh_trang'=>1,'so_luot_toi_da'=>200, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 5: VOUCHER HẠN CHẾ / ĐÃ HẾT HẠN (tinh_trang=0)
            // =====================================================

            ['id'=>39,'ma_code'=>'OLD2024',     'ten_voucher'=>'Ưu Đãi Cuối Năm 2024 (Hết HH)',         'mo_ta'=>'Voucher đã hết hạn từ cuối 2024',                   'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2024-12-01','thoi_gian_ket_thuc'=>'2024-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>0,'so_luot_toi_da'=>100, 'so_luot_da_dung'=>100,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>40,'ma_code'=>'SOLD100',     'ten_voucher'=>'Flash Sale Đã Hết Lượt',                'mo_ta'=>'Voucher đã hết 100 lượt sử dụng',                   'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-05-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>45,'so_tien_toi_da'=>90000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>0,'so_luot_toi_da'=>100, 'so_luot_da_dung'=>100,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 6: VOUCHER SYSTEM / REFERRAL
            // =====================================================

            ['id'=>41,'ma_code'=>'REFERRAL30K', 'ten_voucher'=>'Giới Thiệu Bạn Bè - Tặng 30K',          'mo_ta'=>'Mã giới thiệu: bạn và người được mời đều nhận 30K', 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>0,'so_giam_gia'=>30000,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'referral'],
            ['id'=>42,'ma_code'=>'SYSTEM10',    'ten_voucher'=>'Voucher Hệ Thống 10%',                  'mo_ta'=>'Mã do hệ thống cấp tự động cho sự kiện',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'system'],

            // =====================================================
            // NHÓM 7: THÊM VOUCHER QUÁN LẺ
            // =====================================================

            ['id'=>43,'ma_code'=>'TRASUA20',    'ten_voucher'=>'Trà Sữa Dinhtea - Mua 2 Tặng 20%',      'mo_ta'=>'Mua từ 2 ly trở lên tại Dinhtea, giảm 20%',         'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>3, 'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>44,'ma_code'=>'GONGCHA25K',  'ten_voucher'=>'Gong Cha - Giảm 25K',                   'mo_ta'=>'Giảm 25.000đ khi đặt Gong Cha từ 80k',              'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-04-01','thoi_gian_ket_thuc'=>'2025-09-30','id_quan_an'=>4, 'loai_giam'=>0,'so_giam_gia'=>25000,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>200, 'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>45,'ma_code'=>'NUOCEP15',    'ten_voucher'=>'Nước Ép SG - Giảm 15%',                 'mo_ta'=>'Giảm 15% khi đặt nước ép và sinh tố Sài Gòn',       'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>5, 'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>25000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>46,'ma_code'=>'COMTAM2_15', 'ten_voucher'=>'Cơm Tấm Sườn Ngon - 15%',               'mo_ta'=>'No nê sườn ngon với giảm giá 15%',                  'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>7, 'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>35000,'don_hang_toi_thieu'=>70000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>47,'ma_code'=>'COMCHIEN10',  'ten_voucher'=>'Cơm Chiên ĐN - Giảm 10%',               'mo_ta'=>'Giảm 10% cho các món cơm chiên thơm ngon',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>9, 'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>50000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>48,'ma_code'=>'COMVP20K',    'ten_voucher'=>'Cơm Văn Phòng - Tặng 20K',              'mo_ta'=>'Giảm 20k cho bữa trưa văn phòng tiết kiệm',         'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>10,'loai_giam'=>0,'so_giam_gia'=>20000,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>49,'ma_code'=>'BUNTHIT20',   'ten_voucher'=>'Bún Thịt Nướng - Giảm 20%',             'mo_ta'=>'Bún thơm ngon nướng bếp than, giảm 20%',            'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>12,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>50,'ma_code'=>'BUNCHACA10',  'ten_voucher'=>'Bún Chả Cá Hờn - Giảm 10%',             'mo_ta'=>'Đặc sản chả cá Đà Nẵng, giảm 10% mỗi ngày',        'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>13,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>51,'ma_code'=>'BUNMAM15',    'ten_voucher'=>'Bún Mắm Ngon - Giảm 15%',               'mo_ta'=>'Bún mắm đậm đà, giảm 15% cho tín đồ bún mắm',      'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>14,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>70000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>52,'ma_code'=>'MIQUANGTRANG','ten_voucher'=>'Mì Quảng Bếp Trang - Giảm 20%',         'mo_ta'=>'Mì quảng ếch đặc sản Bếp Trang, giảm 20%',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>17,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>40000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>53,'ma_code'=>'HAISAR30',    'ten_voucher'=>'Hải Sản Cua Biển - Giảm 30%',           'mo_ta'=>'Hải sản tươi sống, giảm sốc 30% cuối tuần',         'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>33,'loai_giam'=>1,'so_giam_gia'=>30,'so_tien_toi_da'=>80000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>54,'ma_code'=>'BETHUI10',    'ten_voucher'=>'Bê Thui Cầu Mống - Giảm 10%',           'mo_ta'=>'Đặc sản bê thui Cầu Mống, giảm 10% mỗi ngày',      'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>34,'loai_giam'=>1,'so_giam_gia'=>10,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>55,'ma_code'=>'BANH5MAU',    'ten_voucher'=>'Tiệm Bánh Kem - Giảm 15%',              'mo_ta'=>'Bánh kem ngọt ngào, giảm 15% nhân dịp đặc biệt',    'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>40,'loai_giam'=>1,'so_giam_gia'=>15,'so_tien_toi_da'=>35000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],

            // =====================================================
            // NHÓM 8: VOUCHER COMBO / ĐẶC BIỆT
            // =====================================================

            ['id'=>56,'ma_code'=>'COMBO2GET20', 'ten_voucher'=>'Mua 2 Combo Giảm 20%',                  'mo_ta'=>'Đặt 2 combotrở lên, giảm ngay 20%',                 'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>60000,'don_hang_toi_thieu'=>150000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>57,'ma_code'=>'BIGORDER25',  'ten_voucher'=>'Đơn Lớn Giảm 25%',                     'mo_ta'=>'Giảm 25% cho đơn hàng từ 200.000đ trở lên',         'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>25,'so_tien_toi_da'=>80000,'don_hang_toi_thieu'=>200000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>2,'loai_voucher'=>'public' ],
            ['id'=>58,'ma_code'=>'FAMILY5',     'ten_voucher'=>'Đơn Gia Đình Giảm 5%',                  'mo_ta'=>'Gọi cả nhà, đơn 5 người cùng giảm 5%',             'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>5, 'so_tien_toi_da'=>20000,'don_hang_toi_thieu'=>100000,'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>3,'loai_voucher'=>'public' ],
            ['id'=>59,'ma_code'=>'LUNCH12H',    'ten_voucher'=>'Bữa Trưa Văn Phòng - Giảm 12%',        'mo_ta'=>'Đặt từ 11h-13h, giảm 12% cho bữa trưa văn phòng',  'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>12,'so_tien_toi_da'=>30000,'don_hang_toi_thieu'=>60000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
            ['id'=>60,'ma_code'=>'MIDNIGHT20',  'ten_voucher'=>'Đêm Khuya Giảm 20%',                   'mo_ta'=>'Đặt từ 22h-24h giảm 20%, phục vụ cú đêm',          'hinh_anh'=>$img,'thoi_gian_bat_dau'=>'2025-01-01','thoi_gian_ket_thuc'=>'2026-12-31','id_quan_an'=>0,'loai_giam'=>1,'so_giam_gia'=>20,'so_tien_toi_da'=>50000,'don_hang_toi_thieu'=>80000, 'tinh_trang'=>1,'so_luot_toi_da'=>null,'so_luot_da_dung'=>0,'so_luot_moi_nguoi'=>1,'loai_voucher'=>'public' ],
        ]);
    }
}
